### ISSUE TITLE
Since apps are not support, hide the "Apps" menu 

### ISSUE THREAD

**Issue by robvanmieghem** [gowncloud/gowncloud#18]
<img width="527" alt="screen shot 2017-02-08 at 17 01 44" src="https://cloud.githubusercontent.com/assets/3511318/22745399/ba6c7904-ee20-11e6-8da6-2dd242f1c1b5.png">
Or just remove it from the html entirely.

**Comment by LeeSmet** [comment]
98bffbd087fddb5803a25e53cb3a216e7c43425f
